name: emoji_flag_converter
description: A dart library for converting country codes to emoji flags.
version: 1.1.0
homepage: https://github.com/flikkr/emoji_flag_converter

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.8
